version: '3'
services:
  frontend:
    container_name: "hx711_frontend"
    build: ./
    volumes:
      - ./app:/app:rw
      # - ./src:/app/src:rw
      # - ./public:/app/public:rws
      # - ./data:/app/dist:rw
    network_mode: "host"