version: '3'
services:
  frontend:
    container_name: "hx711_frontend"
    build: ./
    volumes:
      - ./src:/app/src:rw
      - ./public:/app/public:rw
      - ./dist:/app/dist:rw
    # command: npm install -g solid-js babel-preset-solid && npx degit solidjs/templates/ts-tailwindcss 
    command: "npm run dev --host"
    network_mode: "host"