version: '3'
services:
  frontend:
    container_name: "hx711_frontend"
    working_dir: "/app"
    image: node:latest
    volumes:
      - ./app:/app:rw
      # - ./src:/app/src:rw
      # - ./public:/app/public:rws
      # - ./data:/app/dist:rw
    network_mode: "host"
    entrypoint: "/app/entrypoint.sh"
