version: '3'
services:
  frontend:
    container_name: "hx711_frontend"
    build: ./
    volumes:
      - ./app:/app:rw
      # - ./src:/app/src:rw
      # - ./public:/app/public:rws
      # - ./data:/app/dist:rw
    # command: npm install -g solid-js babel-preset-solid && npx degit solidjs/templates/ts-tailwindcss 
    command: "npm run dev --host"
    network_mode: "host"